"""initial_powerhouse_schema

Revision ID: 9e00dec3f029
Revises: 
Create Date: 2026-08-28 12:40:57.040583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e00dec3f029'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('established_date', sa.String(length=50), nullable=True),
    sa.Column('company_size', sa.String(length=100), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('annual_turnover', sa.String(length=100), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('primary_activity', sa.Text(), nullable=True),
    sa.Column('secondary_activities', sa.Text(), nullable=True),
    sa.Column('manufacturing_activity', sa.Boolean(), nullable=False),
    sa.Column('import_activities', sa.Boolean(), nullable=False),
    sa.Column('export_activities', sa.Boolean(), nullable=False),
    sa.Column('environmental_impact', sa.String(length=50), nullable=False),
    sa.Column('operating_status', sa.String(length=50), nullable=False),
    sa.Column('has_gst', sa.Boolean(), nullable=False),
    sa.Column('has_msme_registration', sa.Boolean(), nullable=False),
    sa.Column('has_udyam_registration', sa.Boolean(), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('udyam_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_business_name'), 'business_profiles', ['business_name'], unique=False)
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_business_profile_id'), 'alerts', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('application_number', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.String(length=50), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=False)
    op.create_index(op.f('ix_applications_business_profile_id'), 'applications', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('required_documents_count', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_business_profile_id'), 'approvals', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('business_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('analysis_status', sa.String(length=50), nullable=False),
    sa.Column('total_approvals', sa.Integer(), nullable=False),
    sa.Column('high_priority_approvals', sa.Integer(), nullable=False),
    sa.Column('total_compliance_tasks', sa.Integer(), nullable=False),
    sa.Column('total_required_documents', sa.Integer(), nullable=False),
    sa.Column('total_recommended_schemes', sa.Integer(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=False),
    sa.Column('analysis_date', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_analyses_business_profile_id'), 'business_analyses', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_business_analyses_id'), 'business_analyses', ['id'], unique=False)
    op.create_table('compliance_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.String(length=100), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_tasks_business_profile_id'), 'compliance_tasks', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_id'), 'compliance_tasks', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('upload_date', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.String(length=50), nullable=True),
    sa.Column('verification_date', sa.String(length=50), nullable=True),
    sa.Column('renewal_cycle', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_business_profile_id'), 'documents', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('government_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefit', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_reason', sa.JSON(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=50), nullable=False),
    sa.Column('official_source', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_schemes_business_profile_id'), 'government_schemes', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_government_schemes_id'), 'government_schemes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_government_schemes_id'), table_name='government_schemes')
    op.drop_index(op.f('ix_government_schemes_business_profile_id'), table_name='government_schemes')
    op.drop_table('government_schemes')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_business_profile_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_compliance_tasks_id'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_business_profile_id'), table_name='compliance_tasks')
    op.drop_table('compliance_tasks')
    op.drop_index(op.f('ix_business_analyses_id'), table_name='business_analyses')
    op.drop_index(op.f('ix_business_analyses_business_profile_id'), table_name='business_analyses')
    op.drop_table('business_analyses')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_business_profile_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_business_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_business_profile_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_business_name'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
