"""add_users_table_and_auth_fields

Revision ID: ba01a4b9120a
Revises: 9e00dec3f029
Create Date: 2026-09-06 14:00:02.757888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba01a4b9120a'
down_revision: Union[str, None] = '9e00dec3f029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('business_profiles', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('business_profiles', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('business_profiles', sa.Column('business_category', sa.String(length=100), nullable=True))
    op.add_column('business_profiles', sa.Column('image_category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_business_profiles_business_category'), 'business_profiles', ['business_category'], unique=False)
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_business_category'), table_name='business_profiles')
    op.drop_column('business_profiles', 'image_category')
    op.drop_column('business_profiles', 'business_category')
    op.drop_column('business_profiles', 'onboarding_completed')
    op.drop_column('business_profiles', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
